### ISSUE TITLE
Map and migrate current fields of science to a shorter set

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-nerc#92] opened 2023-06-01 15:46 UTC
Currently the list of Fields of Science in ColdFront is more granular than we need.

- [x] Get a mapping of current fields of science to new list, X -> Y. [Here](https://docs.google.com/spreadsheets/d/1wtKMQrkbOd3wNq1vnYercTImJRuhHwR_R842TY7W6Aw/edit#gid=0)
- [ ] Write migration command to transition every project from X to Y.

**Comment by joachimweyl** [comment] 2023-07-19 13:15
duplicate of https://github.com/OCP-on-NERC/operations/issues/136

**Comment by joachimweyl** [comment] 2024-03-04 20:41
@knikolla is this something @QuanMPhm would be a good fit for?

**Comment by knikolla** [comment] 2024-03-04 20:42
> @knikolla is this something @QuanMPhm would be a good fit for?

Yes

**Comment by QuanMPhm** [comment] 2024-03-20 19:17
@knikolla My proposed solution is to make a new management command in `coldfront-plugin-api` which should allow the migration of the fields of sciences regardless of what fields of sciences are currently active in the current Coldfront deployment.

To do so, my plan is that the command's only argument is a csv file containing two columns. The first column is the list of old field names, and the second column is the list of new fields names that the old ones will map onto. This way, we can pick and choose which old field names we want migrated. 

The command will first validate the list of old field names, and migrate the field names on every project.

The command will also have an optional argument (i.e `--export`) to export the list of currently active fields of sciences ("active" meaning it appears on the UI drop-down list) for convenience when making the mapping csv file.

**Comment by joachimweyl** [comment] 2024-03-29 14:14
@QuanMPhm as you were looking for issues this looks like a good one so I have moved it into this sprint, if it ends up not fitting into this sprint just let me know.

**Comment by QuanMPhm** [comment] 2024-03-29 14:22
@joachimweyl I actually just submitted a PR for this issue.

**Closed** 2024-04-12 16:36 UTC
Labels: duplicate
